# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default=False, upload_to='photos')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'photos',
            },
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='photos',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.Photo'),
        ),
    ]
