# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20161223_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=False, upload_to='photo'),
        ),
    ]
