# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_remove_photo_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photos',
        ),
    ]
