# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20161223_2041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
